name: Web App Demo
env:
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  OIDC_SERVICE_ACCOUNT: ${{ secrets.OIDC_SERVICE_ACCOUNT }}
on:
  push:
    branches:
      - main
    paths:
      - "web-app-demo/**"
  pull_request:
    branches:
      - main
    paths:
      - "web-app-demo/**"
permissions: read-all
jobs:
  frontend-unit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-app-demo/Frontend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "latest"
      - name: Install dependencies
        run: npm install
      - name: Install Angular CLI
        run: npm install -g @angular/cli > /dev/null
      - name: Run unit tests
        run: ng test --watch=false --browsers=ChromeHeadless
  backend-unit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-app-demo/Backend
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Export Google Application Credentials
        run: export GOOGLE_APPLICATION_CREDENTIALS="CREDENTIALS"
      - name: Run unit tests
        run: python api/helper_test.py
